AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  SuggestExtensions: false

# Disable filename check since imagekitio-rails.rb is intentional
Naming/FileName:
  Exclude:
    - 'lib/imagekitio-rails.rb'

# Allow longer lines in specs for readability
Layout/LineLength:
  Max: 150
  Exclude:
    - 'spec/**/*'
    - 'imagekitio-rails.gemspec'

# Allow longer blocks in specs
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'Rakefile'
    - 'imagekitio-rails.gemspec'

# Allow longer methods for the two main helper methods and Active Storage service
Metrics/MethodLength:
  Exclude:
    - 'lib/imagekit/rails/helper.rb'
    - 'lib/imagekit/rails/active_storage/service.rb'
    - 'lib/imagekit/rails/active_storage/blob_deletion_callback.rb'

# Allow higher complexity for the two main helper methods and Active Storage service
Metrics/AbcSize:
  Exclude:
    - 'lib/imagekit/rails/helper.rb'
    - 'lib/imagekit/rails/active_storage/service.rb'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'lib/imagekit/rails/helper.rb'

Metrics/PerceivedComplexity:
  Exclude:
    - 'lib/imagekit/rails/helper.rb'

# Allow longer modules/classes for the main helper module and Active Storage service
Metrics/ModuleLength:
  Exclude:
    - 'lib/imagekit/rails/helper.rb'

Metrics/ClassLength:
  Exclude:
    - 'lib/imagekit/rails/active_storage/service.rb'

# Documentation is provided in README and inline comments
Style/Documentation:
  Enabled: false

# Examples are for demonstration, don't enforce strict Ruby style
Style/OpenStructUse:
  Exclude:
    - 'examples/**/*'

Style/FetchEnvVar:
  Enabled: false

Gemspec/DevelopmentDependencies:
  Enabled: false

Gemspec/RequireMFA:
  Enabled: false
