name: CI

on:
  push:
  pull_request:

jobs:
  lint:
    timeout-minutes: 10
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      
      - name: Run lints
        run: ./scripts/lint

  test:
    timeout-minutes: 10
    name: Test
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      
      - name: Run tests
        run: ./scripts/test

  docs:
    timeout-minutes: 10
    name: Documentation
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      
      - name: Generate documentation
        run: bundle exec yard doc
      
      - name: Check documentation coverage
        run: bundle exec yard stats --list-undoc
