name: Publish Gem

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish to RubyGems
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: false
      
      - run: |
          bundle install

      - name: Publish gem
        run: bash ./bin/publish-gem
        env:
          GEM_HOST_API_KEY: ${{ secrets.GEM_HOST_API_KEY }}
